spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: home-texttotext-api
  datasource:
    userdb:
      jdbc-url: ${USER_DB_URL}
      url: ${USER_DB_URL}
      driverClassName: org.postgresql.Driver
      username: ${USER_DB_USERNAME}
      password: ${USER_DB_PASSWORD}
      table-scheme: ${USER_DB_TABLE_SCHEME}
    messagedb:
      jdbc-url: ${MESSAGE_DB_URL}
      url: ${MESSAGE_DB_URL}
      driverClassName: org.postgresql.Driver
      username: ${MESSAGE_DB_USERNAME}
      password: ${MESSAGE_DB_PASSWORD}
      table-scheme: ${MESSAGE_DB_TABLE_SCHEME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
  file:
     path: logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${PORT_NUMBER}

chat:
  max-tokens: ${CHAT_MAX_TOKENS:3000}
  openai:
    base-url: ${OPENAI_BASE_URL}
    chat-url: ${OPENAI_CHAT_URL}
    token: ${OPENAI_TOKEN}
  local:
    base-url: ${LOCAL_BASE_URL}
    chat-url: ${LOCAL_CHAT_URL}

kafka:
  bootstrap-url: ${KAFKA_BOOTSTRAP_URL}
  group: ${KAFKA_GROUP_ID}
  topic:
    request: ${KAFKA_REQUEST_TOPIC_NAME}
    response: ${KAFKA_RESPONSE_TOPIC_NAME}
