spring:
  application:
    name: home-texttotext-api

server:
  port: ${PORT_NUMBER}

chat:
  openai:
    baseUrl: ${OPENAI_BASE_URL}
    chatUrl: ${OPENAI_CHAT_URL}
    token: ${OPENAI_TOKEN}
  local:
    baseUrl: ${LOCAL_BASE_URL}
    chatUrl: ${LOCAL_CHAT_URL}