spring:
  application:
    name: home-texttotext-api

server:
  port: ${PORT_NUMBER}

chat:
  openai:
    base-url: ${OPENAI_BASE_URL}
    chat-url: ${OPENAI_CHAT_URL}
    token: ${OPENAI_TOKEN}
  local:
    base-url: ${LOCAL_BASE_URL}
    chat-url: ${LOCAL_CHAT_URL}

kafka:
  bootstrap-url: ${KAFKA_BOOTSTRAP_URL}
  group: ${KAFKA_GROUP_ID}
  topic:
    incoming: ${KAFKA_TOPIC_NAME}
